"""add_leaderboard_model

Revision ID: 1d1fad859878
Revises: 5bcf50dbb7a5
Create Date: 2026-05-20 15:33:54.362024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1fad859878'
down_revision: Union[str, None] = '5bcf50dbb7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_weekly_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_weekly_entry_date'), 'leaderboard_weekly_entry', ['date'], unique=False)
    op.create_index(op.f('ix_leaderboard_weekly_entry_id'), 'leaderboard_weekly_entry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_weekly_entry_id'), table_name='leaderboard_weekly_entry')
    op.drop_index(op.f('ix_leaderboard_weekly_entry_date'), table_name='leaderboard_weekly_entry')
    op.drop_table('leaderboard_weekly_entry')
    # ### end Alembic commands ###
