"""add_is_active_player_status

Revision ID: 3d9783c55787
Revises: 8ca5e0286961
Create Date: 2026-06-25 22:37:09.637426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9783c55787'
down_revision: Union[str, None] = '8ca5e0286961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_score_id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('matchday_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_team.id'], ),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchday.id'], ),
    sa.ForeignKeyConstraint(['player_score_id'], ['player_score.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_score_history_id'), 'player_score_history', ['id'], unique=False)
    op.add_column(
        'fantasy_player',
        sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true())
    )

    # 2. Backfill any rows that might still be NULL (belt and suspenders)
    op.execute('UPDATE fantasy_player SET is_active = TRUE WHERE is_active IS NULL')

    # 3. Now enforce NOT NULL
    op.alter_column('fantasy_player', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_player', 'is_active')
    op.drop_index(op.f('ix_player_score_history_id'), table_name='player_score_history')
    op.drop_table('player_score_history')
    # ### end Alembic commands ###
