"""add_formation_id

Revision ID: 8ca5e0286961
Revises: 13c20a7edb44
Create Date: 2026-06-07 20:28:52.859507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca5e0286961'
down_revision: Union[str, None] = '13c20a7edb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_player_id', sa.Integer(), nullable=False),
    sa.Column('matchday_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_player_id'], ['fantasy_player.id'], ),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchday.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_player_id', 'matchday_id')
    )
    op.create_index(op.f('ix_player_points_id'), 'player_points', ['id'], unique=False)
    op.add_column('fantasy_team', sa.Column('formation_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_team', 'formation_id')
    op.drop_index(op.f('ix_player_points_id'), table_name='player_points')
    op.drop_table('player_points')
    # ### end Alembic commands ###
