"""add_user_role

Revision ID: a8a3de71802a
Revises: 56a2e20d9ea9
Create Date: 2026-04-19 23:30:52.511328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a3de71802a'
down_revision: Union[str, None] = '56a2e20d9ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = sa.Enum('user', 'admin', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', userrole, nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    userrole = sa.Enum('user', 'admin', name='userrole')
    userrole.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
