"""add_private_leagues

Revision ID: b015fe78eacd
Revises: 1d1fad859878
Create Date: 2026-05-20 22:44:55.804724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b015fe78eacd'
down_revision: Union[str, None] = '1d1fad859878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_league_id'), 'private_league', ['id'], unique=False)
    op.create_index(op.f('ix_private_league_join_code'), 'private_league', ['join_code'], unique=True)
    op.create_index(op.f('ix_private_league_name'), 'private_league', ['name'], unique=False)
    op.create_table('private_league_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_league_id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_team.id'], ),
    sa.ForeignKeyConstraint(['private_league_id'], ['private_league.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('private_league_id', 'fantasy_team_id', name='uq_private_league_fantasy_team')
    )
    op.create_index(op.f('ix_private_league_membership_id'), 'private_league_membership', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_private_league_membership_id'), table_name='private_league_membership')
    op.drop_table('private_league_membership')
    op.drop_index(op.f('ix_private_league_name'), table_name='private_league')
    op.drop_index(op.f('ix_private_league_join_code'), table_name='private_league')
    op.drop_index(op.f('ix_private_league_id'), table_name='private_league')
    op.drop_table('private_league')
    # ### end Alembic commands ###
