"""add_round_of_16_32_64_to_phase_name

Revision ID: e33a86c6be5e
Revises: f3a79af0acac
Create Date: 2026-05-01 20:58:15.387550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33a86c6be5e'
down_revision: Union[str, None] = 'f3a79af0acac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
