"""Add matchday deadline

Revision ID: f3a79af0acac
Revises: f96d6ec87ad6
Create Date: 2026-04-27 22:50:49.092677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a79af0acac'
down_revision: Union[str, None] = 'f96d6ec87ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchday', sa.Column('deadline_utc', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchday', 'deadline_utc')
    # ### end Alembic commands ###
