"""Add transfers and system config

Revision ID: f96d6ec87ad6
Revises: a8a3de71802a
Create Date: 2026-04-27 21:26:33.365721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96d6ec87ad6'
down_revision: Union[str, None] = 'a8a3de71802a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('matchday_id', sa.Integer(), nullable=False),
    sa.Column('player_in_id', sa.Integer(), nullable=False),
    sa.Column('player_out_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_team.id'], ),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchday.id'], ),
    sa.ForeignKeyConstraint(['player_in_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_out_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_id'), 'transfer', ['id'], unique=False)
    op.add_column('matchday', sa.Column('task_id', sa.String(), nullable=True))
    op.add_column('matchday', sa.Column('task_status', sa.String(), nullable=True))
    op.add_column('player_score', sa.Column('goals_conceded', sa.Integer(), nullable=False))
    op.add_column('team_score', sa.Column('transfer_penalty', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_score', 'transfer_penalty')
    op.drop_column('player_score', 'goals_conceded')
    op.drop_column('matchday', 'task_status')
    op.drop_column('matchday', 'task_id')
    op.drop_index(op.f('ix_transfer_id'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_table('system_config')
    # ### end Alembic commands ###
