"""predictor

Revision ID: fdfb994017cb
Revises: b015fe78eacd
Create Date: 2026-05-21 06:07:33.503864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfb994017cb'
down_revision: Union[str, None] = 'b015fe78eacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('predicted_home_goals', sa.Integer(), nullable=False),
    sa.Column('predicted_away_goals', sa.Integer(), nullable=False),
    sa.Column('is_joker', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fixture_id', name='uq_user_fixture_prediction')
    )
    op.create_index(op.f('ix_prediction_id'), 'prediction', ['id'], unique=False)
    op.create_table('prediction_matchday_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matchday_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('joker_used', sa.Boolean(), nullable=False),
    sa.Column('joker_applied_to_fixture_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['joker_applied_to_fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchday.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'matchday_id', name='uq_user_matchday_stats')
    )
    op.create_index(op.f('ix_prediction_matchday_stats_id'), 'prediction_matchday_stats', ['id'], unique=False)
    op.create_table('prediction_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exact_score_points', sa.Integer(), nullable=True),
    sa.Column('correct_outcome_points', sa.Integer(), nullable=True),
    sa.Column('joker_multiplier_applied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index(op.f('ix_prediction_score_id'), 'prediction_score', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_score_id'), table_name='prediction_score')
    op.drop_table('prediction_score')
    op.drop_index(op.f('ix_prediction_matchday_stats_id'), table_name='prediction_matchday_stats')
    op.drop_table('prediction_matchday_stats')
    op.drop_index(op.f('ix_prediction_id'), table_name='prediction')
    op.drop_table('prediction')
    # ### end Alembic commands ###
